config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'articles#index'

  resources :articles, only: [:index]
  resources :searches, only: [:index] do
    get :search_history, on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  scope :by_title, ->(search) { where('title ILIKE ?', "%#{search}%") }

  validates :title, :content, presence: true
end

app/models/search.rb
class Search < ApplicationRecord
  belongs_to :user

  scope :trending, -> { select('query, COUNT(*)').group(:query).order(Arel.sql('COUNT(*) DESC')).limit(10) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :searches

  validates :ip_address, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  private

  def current_user
    @current_user ||= begin
      ip = request.headers['X-Forwarded-For'].presence&.split(',')&.first&.strip || request.remote_ip
      User.find_or_create_by(ip_address: ip)
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :process_search_query, if: -> { params[:search].present? }

  def index
    @articles = fetch_articles
  end

  private

  def process_search_query
    # Service to save the search query and avoid duplicates or similar queries
    QueryService.new(current_user, params[:search]).generate
  end

  def fetch_articles
    params[:search].present? ? Article.by_title(params[:search]) : Article.all.limit(20)
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def index
    @trending = Search.trending
  end

  def search_history
    @searches = current_user.searches.order(updated_at: :desc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_articles.html.erb
<ul class="container mx-auto pt-6">
  <% articles.each do |article| %>
    <li class="py-2 border rounded mb-3 shadow p-2">
      <h3 class="text-lg font-semibold"><%= article.title %></h3>
      <p class="text-gray-500"><%= article.content %></p>
    </li>
  <% end %>
</ul>

app/views/articles/index.html.erb
<h1 class="font-semibold text-4xl">Articles:</h1>
<div class="container mx-auto pt-6">
  <%= form_with url: articles_path, method: :get, data: { controller: "search", turbo_frame: "search_results", search_target: "search" } do |form| %>
    <%= form.text_field :search, placeholder: "Search articles...", data: { action: "input->search#perform" }, class: "w-full px-4 py-2 text-xl border border-gray-300 rounded shadow" %>
  <% end %>

  <%= turbo_frame_tag "search_results" do %>
    <%= render partial: "articles", locals: { articles: @articles } %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Helpjuice Search Box</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <main class="container max-w-7xl mx-auto mt-28 px-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/searches/_search.html.erb
<% searches.each do |search| %>
  <div class="flex justify-between items-center border shadow rounded p-4 mb-4">
    <span class="text-gray-700 text-lg"><%= search.query %></span>
    <span class="border text-blue-800 text-sm font-semibold mr-2 px-2.5 py-0.5 rounded">
      <% if search.respond_to?(:count) %>
        <%= search.count %> times
      <% else %>
        <%= time_ago_in_words(search.updated_at) %> ago
      <% end %>
    </span>
  </div>
<% end %>

app/views/searches/index.html.erb
<div class="max-w-md mx-auto mt-10 flex justify-center flex-col">
  <h1 class="font-semibold text-4xl text-center ">Trending</h1>
  <p class="mb-4 text-gray-500 text-center">The most popular searches right now</p>
  <%= render partial: "search", locals: { searches: @trending } %>
</div>

app/views/searches/search_history.html.erb
<div class="max-w-md mx-auto mt-10 flex justify-center flex-col">
  <h1 class="font-semibold text-4xl text-center ">Search History</h1>
  <p class="mb-4 text-gray-500 text-center">A Look Back at Your Searches</p>
  <%= render partial: "search", locals: { searches: @searches } %>
</div>

app/views/shared/_navbar.html.erb
<nav class="bg-blue-600 fixed top-0 w-full shadow">
  <div class="max-w-7xl mx-auto px-2 sm:px-6 lg:px-8">
    <div class="flex py-4">
      <%= link_to "Articles", root_path, class: "text-gray-100 hover:bg-blue-700 hover:text-white px-3 py-2 rounded-md text-sm" %>
      <%= link_to "Trending", searches_path, class: "text-gray-100 hover:bg-blue-700 hover:text-white px-3 py-2 rounded-md text-sm" %>
      <%= link_to "Search History", search_history_searches_path, class: "text-gray-100 hover:bg-blue-700 hover:text-white px-3 py-2 rounded-md text-sm" %>
    </div>
  </div>
</nav>